kind = "web"
previewPath = "/"
title = "KARUWORKS"
version = "1.0.0"
id = "artifacts/karuworks"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25989

[services.development]
run = "pnpm --filter @workspace/karuworks run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/karuworks", "run", "build" ]
publicDir = "artifacts/karuworks/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25989"
BASE_PATH = "/"
